# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: default

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        cd Chamomile/
        npm install -g @angular/cli@16.2.14
        npm install
        ng build
      displayName: 'npm install and build'
      workingDirectory: '$(Build.SourcesDirectory)'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/chamomile/'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        MaxArtifactSize: 0

- stage: Development
  displayName: 'Deploy to Development'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentDevelopment
    pool:
      vmImage: 'ubuntu-latest'
    environment: Development
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Suscripción de Azure 1(3a9ee721-4423-43cb-9efb-ddaefd3c364e)'
              appType: 'webAppLinux'
              appName: 'chmmile'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              runtimeStack: 'NODE|18-lts'
              
          - script: |
              docker run -d --expose=80 -p 80:80 --name chmmile_1_2fcaa7f7 \
              -e WEBSITE_USE_DIAGNOSTIC_SERVER=true \
              -e WEBSITE_SITE_NAME=chmmile \
              -e WEBSITE_AUTH_ENABLED=False \
              -e WEBSITE_ROLE_INSTANCE_ID=0 \
              -e WEBSITE_HOSTNAME=chmmile.azurewebsites.net \
              -e WEBSITE_INSTANCE_ID=547ad6530bcf318c7dcff9f278abe48477eb1a6d4d5cf3e0f863a095bd0eac2b \
              -e NODE_OPTIONS=--require /agents/nodejs/build/src/Loader.js \
              appsvc/node:18-lts_20240321.5.tuxprod pm2 serve /home/site/wwwroot -no-daemon-spa
            displayName: 'Run Docker container with custom port'

- stage: Acceptance
  dependsOn: [ Development ]
  displayName: 'Deploy to Acceptance'
  jobs:
    - job:  DeployToAcceptance
      displayName: 'DeployAcceptance'
      steps:
      - checkout: self
      - script: echo Deploying to Acceptance

- stage: Production
  dependsOn: [ Acceptance ]
  displayName: 'Deploy to Production'
  jobs:
    - deployment: DeployProduction
      pool:
        vmImage: 'ubuntu-latest'
      environment: Production
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - script: echo Deploying to Production
