# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js version 20.12.2
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Install Angular CLI v16.2.14
        run: npm install -g @angular/cli@16.2.14

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --configuration production

      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
